version: "3"
services:
  server:
    build: .\server
    environment:
      - HOST=server
      - PORT=80
      - WORKER_CONNECTIONS=10 #number of worker connections that server supports simultaneously
      - CONNECTION_TIMEOUT=5 # timeout in seconds that server keeps per each connection
    ports:
      - "8181:80"
  attacker:
    build: .\attacker
    environment:
      - SOCKETS=100
      - HOST=server
      - PORT=80
      - SLEEP_TIME=30 # sleep time in seconds between another attempt to send keep-alive header
