version: "3"
services:
  mariadb:
    image: mariadb
    container_name: mariadb-hw8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - ~/Dev/data/mariadb-hw8:/var/lib/mysql
    ports:
      - 3306:3306
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    depends_on:
      - mariadb
    ports:
      - 8080:8080