/**/callback({
  "meta": {
    "Content-Type": "application/javascript; charset=utf-8",
    "X-RateLimit-Limit": "60",
    "X-RateLimit-Remaining": "59",
    "X-RateLimit-Reset": "1575025844",
    "Cache-Control": "public, max-age=60, s-maxage=60",
    "Vary": "Accept",
    "ETag": "\"3e14b87fdf0b3839d4fd0ace44d24435\"",
    "Last-Modified": "Fri, 29 Nov 2019 09:59:09 GMT",
    "X-GitHub-Media-Type": "github.v3; format=json",
    "status": 200
  },
  "data": {
    "id": 41881900,
    "node_id": "MDEwOlJlcG9zaXRvcnk0MTg4MTkwMA==",
    "name": "vscode",
    "full_name": "microsoft/vscode",
    "private": false,
    "owner": {
      "login": "microsoft",
      "id": 6154722,
      "node_id": "MDEyOk9yZ2FuaXphdGlvbjYxNTQ3MjI=",
      "avatar_url": "https://avatars2.githubusercontent.com/u/6154722?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/microsoft",
      "html_url": "https://github.com/microsoft",
      "followers_url": "https://api.github.com/users/microsoft/followers",
      "following_url": "https://api.github.com/users/microsoft/following{/other_user}",
      "gists_url": "https://api.github.com/users/microsoft/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/microsoft/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/microsoft/subscriptions",
      "organizations_url": "https://api.github.com/users/microsoft/orgs",
      "repos_url": "https://api.github.com/users/microsoft/repos",
      "events_url": "https://api.github.com/users/microsoft/events{/privacy}",
      "received_events_url": "https://api.github.com/users/microsoft/received_events",
      "type": "Organization",
      "site_admin": false
    },
    "html_url": "https://github.com/microsoft/vscode",
    "description": "Visual Studio Code",
    "fork": false,
    "url": "https://api.github.com/repos/microsoft/vscode",
    "forks_url": "https://api.github.com/repos/microsoft/vscode/forks",
    "keys_url": "https://api.github.com/repos/microsoft/vscode/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/microsoft/vscode/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/microsoft/vscode/teams",
    "hooks_url": "https://api.github.com/repos/microsoft/vscode/hooks",
    "issue_events_url": "https://api.github.com/repos/microsoft/vscode/issues/events{/number}",
    "events_url": "https://api.github.com/repos/microsoft/vscode/events",
    "assignees_url": "https://api.github.com/repos/microsoft/vscode/assignees{/user}",
    "branches_url": "https://api.github.com/repos/microsoft/vscode/branches{/branch}",
    "tags_url": "https://api.github.com/repos/microsoft/vscode/tags",
    "blobs_url": "https://api.github.com/repos/microsoft/vscode/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/microsoft/vscode/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/microsoft/vscode/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/microsoft/vscode/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/microsoft/vscode/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/microsoft/vscode/languages",
    "stargazers_url": "https://api.github.com/repos/microsoft/vscode/stargazers",
    "contributors_url": "https://api.github.com/repos/microsoft/vscode/contributors",
    "subscribers_url": "https://api.github.com/repos/microsoft/vscode/subscribers",
    "subscription_url": "https://api.github.com/repos/microsoft/vscode/subscription",
    "commits_url": "https://api.github.com/repos/microsoft/vscode/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/microsoft/vscode/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/microsoft/vscode/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/microsoft/vscode/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/microsoft/vscode/contents/{+path}",
    "compare_url": "https://api.github.com/repos/microsoft/vscode/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/microsoft/vscode/merges",
    "archive_url": "https://api.github.com/repos/microsoft/vscode/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/microsoft/vscode/downloads",
    "issues_url": "https://api.github.com/repos/microsoft/vscode/issues{/number}",
    "pulls_url": "https://api.github.com/repos/microsoft/vscode/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/microsoft/vscode/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/microsoft/vscode/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/microsoft/vscode/labels{/name}",
    "releases_url": "https://api.github.com/repos/microsoft/vscode/releases{/id}",
    "deployments_url": "https://api.github.com/repos/microsoft/vscode/deployments",
    "created_at": "2015-09-03T20:23:38Z",
    "updated_at": "2019-11-29T09:59:09Z",
    "pushed_at": "2019-11-29T10:03:36Z",
    "git_url": "git://github.com/microsoft/vscode.git",
    "ssh_url": "git@github.com:microsoft/vscode.git",
    "clone_url": "https://github.com/microsoft/vscode.git",
    "svn_url": "https://github.com/microsoft/vscode",
    "homepage": "https://code.visualstudio.com",
    "size": 248318,
    "stargazers_count": 87586,
    "watchers_count": 87586,
    "language": "TypeScript",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 13072,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 4026,
    "license": {
      "key": "mit",
      "name": "MIT License",
      "spdx_id": "MIT",
      "url": "https://api.github.com/licenses/mit",
      "node_id": "MDc6TGljZW5zZTEz"
    },
    "forks": 13072,
    "open_issues": 4026,
    "watchers": 87586,
    "default_branch": "master",
    "organization": {
      "login": "microsoft",
      "id": 6154722,
      "node_id": "MDEyOk9yZ2FuaXphdGlvbjYxNTQ3MjI=",
      "avatar_url": "https://avatars2.githubusercontent.com/u/6154722?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/microsoft",
      "html_url": "https://github.com/microsoft",
      "followers_url": "https://api.github.com/users/microsoft/followers",
      "following_url": "https://api.github.com/users/microsoft/following{/other_user}",
      "gists_url": "https://api.github.com/users/microsoft/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/microsoft/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/microsoft/subscriptions",
      "organizations_url": "https://api.github.com/users/microsoft/orgs",
      "repos_url": "https://api.github.com/users/microsoft/repos",
      "events_url": "https://api.github.com/users/microsoft/events{/privacy}",
      "received_events_url": "https://api.github.com/users/microsoft/received_events",
      "type": "Organization",
      "site_admin": false
    },
    "network_count": 13072,
    "subscribers_count": 2862
  }
})
