version: "3"
services:
  nginx:
    build: ./nginx
    container_name: nginx
    volumes:
      - ~/Dev/data/nginx/logs:/tmp/logs
    ports:
      - 8081:8080
    restart: always
    sysctls:
      - net.core.somaxconn=512
      - net.core.netdev_max_backlog=2000
      - net.ipv4.ip_local_port_range = 1024 65000
    depends_on:
      - db-reader-1
      - db-reader-2
      - db-reader-3
####-------monitoring-------
  influxdb:
    image: influxdb
    container_name: influxdb
    ports:
      - 8086:8086
    volumes:
      - ~/Dev/data/influxdb:/var/lib/influxdb
  grafana:
      image: grafana/grafana
      container_name: grafana
      ports:
        - 3000:3000
      volumes:
        - grafana-storage:/var/lib/grafana
  telegraf:
      image: telegraf
      container_name: telegraf
      volumes:
        - ~/Dev/high-load-arch/hw4/telegraf.conf:/etc/telegraf/telegraf.conf:ro
        - /var/run/docker.sock:/var/run/docker.sock

volumes: 
  grafana-storage: